arch: linear
aug: true
augmentation: RandomCrop
batch_size: 255
ckpt: ''
ckpt_iter: -1
config_file: null
data: imagenet
dist: dp
# dist_address: 127.0.0.1:1234
dist_address: 'env://'
encode_layer: h
encoder_ckpt: "/home/liweiquan/simclr-pytorch-master/simclr-pytorch-master/logs/exman-train.py/runs/000015/checkpoint.pth.tar"
eval_freq: 1960
finetune: false
iters: 39200
log_freq: 392
lr: 0.8
lr_schedule: warmup-anneal
model_id: -1
n_augs_test: 50
n_augs_train: 10
name: ''
node_rank: 0
opt: lars
precompute_emb_bs: -1
problem: eval
root: ''
save_freq: 1960
scale_lower: 0.2
seed: -1
status: fail
test_bs: 255
tmp: false
warmup: 0.0
weight_decay: 0
workers: 2
world_size: 1
