arch: resnet18
aug: true
batch_size: 255
ckpt: "/home/liweiquan/simclr-pytorch-master/simclr-pytorch-master/logs/exman-train.py/runs/000013/checkpoint.pth.tar"
color_dist_s: 0.5
config_file: null
data: imagenet
dist: ddp
# dist_address: '127.0.0.1:1234'
dist_address: 'env://'
eval_freq: 1960
iters: 39200
log_freq: 196
lr: 0.1
lr_schedule: warmup-anneal
multiplier: 2
name: 'reproduce-cifar10'
node_rank: 0
opt: sgd
problem: sim-clr
root: 'none'
save_freq: 1960
scale_lower: 0.2
seed: -1
sync_bn: true
temperature: 1.0
tmp: false
verbose: true
warmup: 0
weight_decay: 0.0001
workers: 2
world_size: 1